### ISSUE TITLE
Icons are not scaled properly

### ISSUE THREAD

**Issue by wedens** [jojojames/vscode-icon-emacs#1]
When I execute this code from the readme:
```elisp
(setq json-image (vscode-icon-for-file "somejsonfile.json"))
(insert-image json-image)
```

Huge (128x128?) icon is being inserted.

![image](https://user-images.githubusercontent.com/697162/49338220-4d08b400-f651-11e8-8d9d-466c7c33da85.png)

I  also have scaling issues with dired-sidebar with vscode icons:
![image](https://user-images.githubusercontent.com/697162/49338238-71649080-f651-11e8-9569-d9ebdb43b053.png)

`(vscode-icon-can-scale-image-p)` returns `t`

emacs 27.0.50 with imagemagick support
vscode-icon-emacs 3ad83ee (HEAD)
dired-sidebar `f778241` (HEAD)

**Comment by tSte** [comment]
I have this problem also with custom scaled icons.
I [scaled them to 16](https://github.com/jojojames/vscode-icon-emacs#using-different-sized-icons) and tried to insert `(setq vscode-icon-size 16)` to `dotspacemacs/user-config` and `user-init` but I still have same size.
Am I doing something wrong?
Are those icons stored somewhere else? Because when I removed `128` folder, nothing happened.

**Comment by jojojames** [comment]
Woops, sorry this slipped past me.
Linux or OSX?

**Comment by wedens** [comment]
Linux in my case.

**Comment by jojojames** [comment]
OK, I think I've seen this too on one of my linux machines. I'm not sure if the imagemagick scaling works for some reason on it...

It might take me a while to look at this though so if you want to try and root cause further, that'd be awesome!

**Comment by sheikki** [comment]
Same issue here on CentOS 7, Emacs 26.2 built with imagemagic support

**Comment by jojojames** [comment]
K, my hands are tied until I have time to look at it on a linux machine. I'd recommend if someone has the motivation to dig into the scaling code. :D

**Comment by jojojames** [comment]
If you guys build Emacs 27, what does (image-transforms-p) return?
