### ISSUE TITLE
Light version and svg version

### ISSUE THREAD

**Issue by casouri** [jojojames/vscode-icon-emacs#6]
Thanks for this package! I like image icons as they don't require you to install any fonts.

I wonder if it's possible to add support for light versions of the icons? And since Emacs supports svg since (I think?) Emacs 28, it would be nice to be able to use the original svg files.

**Comment by jojojames** [comment]
I probably don't have all the light icons in thsi repo right?

The SVG stuff sounds interesting too. Open to PR on any of these features but don't have time right now to implement.

**Comment by casouri** [comment]
I had a look and it seems all the light and opened variants are already in the repo. I submitted a patch that opens access to them, take a look! I'm not sure about interfacing the svg variants yet. Should they be configured by a variable, like `vscode-icon-file-type`, or passed as an argument?

**Comment by jojojames** [comment]
> I'm not sure about interfacing the svg variants yet. Should they be configured by a variable, like vscode-icon-file-type, or passed as an argument?

Oops, left this hanging. Not sure, no opinion on it. Either is fine. 

Closing this now and open to a PR if you want to re pursue this. Thanks!
