### ISSUE TITLE
Update VSCode icons

### ISSUE THREAD

**Issue by gekoke** [jojojames/vscode-icon-emacs#8]
It seems that the icons haven't been updated in 5 years. It would be nice to add the icons that have been added since - there are 1246 icons in the upstream repo at the time of writing.

The file associations could be programmatically parsed from [here](https://github.com/vscode-icons/vscode-icons/blob/master/src/iconsManifest/languages.ts) and [here](https://github.com/vscode-icons/vscode-icons/blob/master/src/iconsManifest/supportedExtensions.ts).

I could try and help with this effort if this is something you would like to implement - perhaps not right at this very moment, but definitely some time in the future.

**Comment by jojojames** [comment]
Added the new images, feel free to PR any file associations.
